#!/usr/bin/env python
from sys import path
from os.path import dirname, join
path.append(join(dirname(__file__), '..'))

from matplotlib.pyplot import axis, imshow, show, subplot, title
from numpy import amax, amin, minimum
from fauxton import DepthSensor, SurfaceNormalSensor, read_scene

#===============================================================================
# Rendering
#===============================================================================

scene_path = join(dirname(__file__), 'scene.blend')
scene = read_scene(scene_path)

optical_sensor = scene['Camera']
normal_sensor = scene.add(SurfaceNormalSensor(pose=optical_sensor.pose))
depth_sensor = scene.add(DepthSensor(pose=optical_sensor.pose))

optical_image = optical_sensor.render()
normal_image = normal_sensor.render()
depth_image = depth_sensor.render()

#===============================================================================
# Visualization
#===============================================================================

subplot(1, 3, 1); axis('off'); title('Optical Image')
imshow(optical_image)

subplot(1, 3, 2); axis('off'); title('Surface Normals');
imshow(normal_image / 2.0 + 0.5)

subplot(1, 3, 3); axis('off'); title('Depth');
imshow(depth_image, vmax=8.0, cmap='gray')

show()
