#!/usr/bin/env python
from sys import path
from os.path import dirname, join
path.append(join(dirname(__file__), '..'))

from matplotlib.pyplot import axis, imshow, show, title
from fauxton import read_scene

#===============================================================================
# Rendering
#===============================================================================

scene_path = join(dirname(__file__), 'scene.blend')
camera = read_scene(scene_path)['Camera']

camera.source = '''
    shader pattern(output color result = color(0))
      { result = noise("uperlin", 5 * u, 5 * v); }
  '''

#===============================================================================
# Visualization
#===============================================================================

imshow(camera.render())
title('Texture Generated with OSL')
axis('off')
show()
