#!/usr/bin/env python
from sys import path
from os.path import dirname, join
path.append(join(dirname(__file__), '..'))

from shutil import rmtree
from tempfile import mkdtemp
from fauxton import DepthSensor, Scene, read_scene, write_scene

#===============================================================================
# Scene Building
#===============================================================================

scene = Scene()
scene['depth_sensor'] = DepthSensor()
scene['depth_sensor'].position = (1, 2, 3)

#===============================================================================
# Scene Writing
#===============================================================================

scene_dir = mkdtemp()
scene_path = join(scene_dir, 'scene.blend')
write_scene(scene_path, scene)

#===============================================================================
# Scene Reading and File System Cleanup
#===============================================================================

scene = read_scene(scene_path)
rmtree(scene_dir)

#===============================================================================
# Scene Inspection
#===============================================================================

assert 'depth_sensor' in scene
assert type(scene['depth_sensor']) is DepthSensor
assert tuple(scene['depth_sensor'].position) == (1, 2, 3)
